---
# tasks file for roles/fluentd

- name: Import a key for fluentd
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.treasuredata.com/GPG-KEY-fluent-package
  when: ansible_os_family == 'RedHat'

- name: epel | setup dnf repository
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      https://s3.amazonaws.com/packages.treasuredata.com/lts/5/redhat/9/x86_64/fluent-package-5.0.2-1.el9.x86_64.rpm
    state: present
  when: ansible_os_family == 'RedHat'

- name: fluentd | install
  become: true
  ansible.builtin.dnf:
    name: "{{ fluentd_name }}"
    state: present
    lock_timeout: "{{ fluentd_dnf_lock_timeout }}"
  notify:
    - restart fluentd

- name: fluentd | add user to groups
  become: true
  user:
    name: td-agent
    append: true
    groups: "{{ item }}"
  with_items: "{{ fluentd_groups }}"
  notify:
    - restart fluentd

- name: fluentd | configuration directory
  become: true
  file:
    path: /etc/{{ fluentd_name }}/conf.d
    state: directory
    mode: 0755

- name: fluentd | main configuration
  become: true
  copy:
    src: fluentd.conf
    dest: /etc/{{ fluentd_name }}/{{ fluentd_name }}.conf
    mode: 0644
  notify:
    - restart fluentd

- name: fluentd | list plugins
  command: /usr/sbin/td-agent-gem list
  register: _fluent_plugins
  changed_when: false
  check_mode: false

- name: fluentd | install fluentd plugins
  become: true
  command: /usr/sbin/td-agent-gem install {{ item }}
  with_items: "{{ fluentd_plugins }}"
  when: item not in _fluent_plugins.stdout
  notify:
    - restart fluentd

- name: fluentd | systemd configuration
  become: true
  file:
    path: /etc/systemd/system/{{ fluentd_name }}.service.d
    state: directory
    mode: 0755

- name: fluentd | systemd configuration environment file
  become: true
  copy:
    src: systemd-fluentd-service-d-env.conf
    dest: /etc/systemd/system/{{ fluentd_name }}.service.d/50-env.conf
    mode: 0644
  notify:
    - restart fluentd

- name: fluentd | environment variables
  become: true
  template:
    src: sysconfig-fluentd.j2
    dest: /etc/sysconfig/fluentd
    owner: root
    group: root
    # May contain sensitive tokens
    mode: 0600
  notify:
    - restart fluentd

- name: fluentd | start service
  become: true
  service:
    enabled: true
    name: "{{ fluentd_name }}"
    state: started

# TODO: service enabled=yes doesn't work for td-agent for unknown reasons
# This is a workaround to manually enable the service
- name: fluentd | workaround service enable bug
  become: true
  file:
    dest: /etc/systemd/system/multi-user.target.wants/td-agent.service
    src: /usr/lib/systemd/system/td-agent.service
    state: link
