---
- name: Converge
  hosts: all

  # Do some pre-test setup
  pre_tasks:
    - name: Import a key for epel
      ansible.builtin.rpm_key:
        state: present
        key:  https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

    - name: epel | setup dnf repository
      become: true
      ansible.builtin.dnf:
        update_cache: true
        name:
          https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present

    - name: install nginx
      become: true
      ansible.builtin.dnf:
        update_cache: true
        name: >-
          nginx
        state: present
      when: ansible_os_family == 'RedHat'

    - name: system packages | install nginx
      become: true
      ansible.builtin.apt:
        update_cache: true
        name: nginx
        state: present
      when: ansible_os_family == 'Debian' 

    - name: start nginx
      become: true
      service:
        enabled: true
        name: nginx
        state: started

    - name: ensure /var/log/nginx is accessible
      become: true
      file:
        path: /var/log/nginx
        mode: "a+rx"

  # Now test the fluentd role deployment
  roles:
    - role: ome.fluentd
      fluentd_groups: nginx
      fluentd_plugins:
        - fluent-plugin-slack
      fluentd_env:
        SLACK_TOKEN: xoxp-SECRET-SLACK-TOKEN
        SLACK_CHANNEL: trash

  tasks:
    - name: copy nginx fluentd config
      become: true
      copy:
        src: fluentd-conf/fluentd-nginx.conf
        dest: /etc/td-agent/conf.d/nginx.conf
        mode: 0644
      notify:
        - restart fluentd
